# .github/workflows/echo.yml
name: Echo Name

on:
  push:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo name
      run: echo "Your Name"
